version: '3.7'

networks:
  monitor-net:

volumes:
    #prometheus_data:
    grafana_data:

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/:/etc/prometheus/
      - ./configs/alert.rules:/etc/prometheus/alert.rules
      - ./data/prometheus:/data
#      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=240h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    # línea adicionada para alertmanager
    depends_on:
       - alertmanager
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./configs:/prometheus
      - ./data:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitor-net
    
  # processmanager:
  #   image: ncabatoff/process-exporter
  #   volumes:
  #   - /proc:/host/proc:ro
  #   - ./config:/config
  #   command:
  #   - '-config.path=/config/filename.yml'
  #   restart: unless-stopped
  #   ports:
  #   - 9256:9256

#   blackboxexporter:
#     image: prom/blackbox-exporter:latest
#     volumes:
#       - ./configs:/etc/blackbox_exporter/
#       - /etc/ssl/certs/:/etc/ssl/certs/:ro
#     command:
#       - '--config.file=/etc/blackbox_exporter/blackbox.yml'
#     restart: unless-stopped
#     ports:
#       - "9115:9115"
#     networks:
#       - monitor-net

  grafana:
    image: grafana/grafana:latest
    volumes:
       - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin  
      - GF_SECURITY_ADMIN_PASSWORD=123qwe  
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    links:
      - prometheus:prometheus
    ports:
      - 3000:3000
    networks:
      - monitor-net

  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk:/dev/disk/:ro
    ports:
      - 8080:8080
    networks:
      - monitor-net    
    depends_on:
    - redis

  redis:
    image: redis:latest
    ports:
    - 6379:6379
    networks:
      - monitor-net    
