global:
  scrape_interval: 5s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager-forum-api:9093

scrape_configs:

- job_name: prometheus-forum-api
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-forum-api:9090

- job_name: app-forum-api
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - app-forum-api:8080

- job_name: windows
  metrics_path: /metrics
  static_configs:
  - targets:
    - host.docker.internal:9182